version: "3.9"
services:
  db:
    container_name: postgresql
    image: postgres:14.5
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${DB_NAME}"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
